server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: # 网关路由配置
        - id: booklist # 路由id
          uri: http://localhost:8020 # 路由的目标地址
          predicates:
            - Path=/booklist/**
      discovery:
        locator:
          enabled: true #默认所有服务转发操作
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
